type User @table {
  username: String!
  email: String!
  bio: String
  avatarUrl: String
}

type Track @table {
  title: String!
  artistName: String!
  externalUrl: String!
  albumName: String
  genre: String
}

type Playlist @table {
  title: String!
  creator: User!
  description: String
  isPublic: Boolean
}

type LoveNote @table {
  playlist: Playlist!
  track: Track!
  message: String!
}

type Heart @table {
  user: User!
  playlist: Playlist!
}

type Follow @table {
  follower: User!
  following: User!
}